---
title: "Plot performance summaries"
author: 
- name: Charlotte Soneson
- name: Angelo Duo
date: "`r Sys.Date()`"
package: DuoClustering2018
output:
  BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Plot performance summaries}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Load the package

```{r}
suppressPackageStartupMessages({
  library(DuoClustering2018)
  library(plyr)
})
```

# Read a set of clustering results

```{r}
res <- plyr::rbind.fill(
  clustering_summary_filteredExpr10_Koh(),
  clustering_summary_filteredHVG10_Koh(),
  clustering_summary_filteredExpr10_Zhengmix4eq(),
  clustering_summary_filteredHVG10_Zhengmix4eq()
)
```

# Define consistent method colors

```{r}
method_colors <- c(CIDR = "#332288", FlowSOM = "#6699CC", PCAHC = "#88CCEE", 
                   PCAKmeans = "#44AA99", pcaReduce = "#117733",
                   RtsneKmeans = "#999933", Seurat = "#DDCC77", SC3svm = "#661100",
                   SC3 = "#CC6677", TSCAN = "grey34",  ascend = "orange", SAFE = "black")
```

# Plot

## Performance

```{r}
perf <- plot_performance(res, method_colors = method_colors)
names(perf)
```

## Stability

```{r}
stab <- plot_stability(res, method_colors = method_colors)
names(stab)
```

## Entropy

```{r}
entr <- plot_entropy(res, method_colors = method_colors)
names(entr)
```

## Timing

```{r}
timing <- plot_timing(res, method_colors = method_colors, scaleMethod = "RtsneKmeans")
names(timing)
```

## Differences in k

```{r}
kdiff <- plot_k_diff(res, method_colors = method_colors)
names(kdiff)
```

# Session info

```{r}
sessionInfo()
```

